window.VIF_LISTENER_PROPERTIES = window.VIF_LISTENER_PROPERTIES || {};
window.VIF_LISTENER_PROPERTIES['ObjectTracking'] = [
    { key: 'id3', label: 'ID3 Tags', type: 'boolean', default: false, tooltip: 'Inject detection results as ID3 timed metadata tags' },
    { key: 'webhooks', label: 'Webhooks', type: 'boolean', default: false, tooltip: 'Send detection results via webhook HTTP POST' },
    { key: 'logfile', label: 'Log File', type: 'boolean', default: false, tooltip: 'Write detection results to log files' },
    { key: 'overlays', label: 'Overlays', type: 'boolean', default: true, tooltip: 'Draw detection overlays on the video stream' },
    { key: 'draw_untracked_objects', label: 'Draw Untracked Objects', type: 'boolean', default: true, tooltip: 'Draw bounding boxes for objects not yet tracked' },
    { key: 'untracked_object_color', label: 'Untracked Object Color', type: 'text', default: 'gray', tooltip: 'Color for untracked object bounding boxes' },
    { key: 'untracked_object_label', label: 'Untracked Object Label', type: 'text', default: '{{track_id}}:{{class_name}} {{confidence}}', tooltip: 'Label template for untracked objects. Variables: {{track_id}}, {{class_name}}, {{confidence}}' },
    { key: 'replace_video', label: 'Replace Video', type: 'boolean', default: true, tooltip: 'Replace the original video with the overlay rendering' },
    { key: 'fade_step', label: 'Fade Step', type: 'number', default: 20, tooltip: 'Number of frames over which overlays fade out' },
    { key: 'title_string', label: 'Title String', type: 'text', default: '', tooltip: 'Title overlay using date format pattern, e.g. \'Cam-01:\' yyyy-MM-dd HH:mm:ss' },
    { key: 'save_image', label: 'Save Image', type: 'boolean', default: false, tooltip: 'Save detection frame images to disk' },
    { key: 'save_image_path', label: 'Save Image Path', type: 'text', default: '', tooltip: 'Directory path for saved detection images' },
    {
        key: 'regions_of_interest',
        label: 'Regions of Interest',
        type: 'array',
        item_label: 'Region',
        fields: [
            { key: 'type', label: 'Type', type: 'select', default: 'box', options: ['box', 'line'], tooltip: 'What type of region this is' },
            { key: 'name', label: 'Name', type: 'text', default: 'The Box', tooltip: 'Display name for this region' },
            { key: 'x', label: 'X', type: 'number', default: 0, tooltip: 'Left coordinate of the region' },
            { key: 'y', label: 'Y', type: 'number', default: 0, tooltip: 'Top coordinate of the region' },
            { key: 'x2', label: 'X2', type: 'number', default: 640, tooltip: 'Right coordinate of the region' },
            { key: 'y2', label: 'Y2', type: 'number', default: 360, tooltip: 'Bottom coordinate of the region' },
            { type: 'separator', label: 'Filters Options' },
            { key: 'class_names', label: 'Class Names', type: 'string_list', default: ['all'], tooltip: 'Object classes to track in this region. Use "all" for all classes' },
            { key: 'confidence_threshold', label: 'Confidence Threshold', type: 'number', default: 0.5, step: 0.05, tooltip: 'Minimum confidence to consider a detection in this region' },
            { key: 'width_threshold', label: 'Width Threshold', type: 'number', default: 0, tooltip: 'Minimum bounding box width (pixels) to include detection' },
            { key: 'height_threshold', label: 'Height Threshold', type: 'number', default: 0, tooltip: 'Minimum bounding box height (pixels) to include detection' },
            { type: 'separator', "label": "Overlay Options" },
            { key: 'draw_region', label: 'Draw Region', type: 'boolean', default: true, tooltip: 'Draw the region boundary on the overlay' },
            { key: 'draw_objects', label: 'Draw Objects', type: 'boolean', default: true, tooltip: 'Draw object bounding boxes inside this region' },
            { key: 'color', label: 'Color', type: 'text', default: 'red', tooltip: 'Color for the region boundary and labels' },
            { key: 'label', label: 'Region Label', type: 'text', default: '{{name}} ({{current}}:{{total}})', tooltip: 'Region label template. Variables: {{name}}, {{current}}, {{total}}' },
            { key: 'object_label', label: 'Object Label', type: 'text', default: '{{track_id}}:{{class_name}} {{confidence}}', tooltip: 'Object label template within this region' },
            { type: 'separator', "label": "Trigger Options" },
            { key: 'triggers', label: 'Triggers', type: 'string_list', default: ["inside"], tooltip: 'Trigger rules, e.g. inside::detected, velocity_min::stalled, direction::wrong way' },
            { key: 'inside_count', label: 'Inside Count', type: 'number', default: 10, tooltip: 'Number of consecutive frames an object must be inside to trigger' },
            { key: 'overlap_count', label: 'Overlap Count', type: 'number', default: 10, tooltip: 'Number of consecutive frames an object must be overlap to trigger' },
            { key: 'object_coordinate', label: 'Object Coordinate', type: 'select', default: 'center-center', options: ['bottom-center', 'bottom-left', 'bottom-right', 'center-center', 'center-left', 'center-right', 'top-center', 'top-left', 'top-right'], tooltip: 'Which point of the object bounding box to use for region checks' },
            { key: 'velocity_min', label: 'Velocity Min', type: 'number', default: 0, tooltip: 'Minimum velocity threshold for stall detection' },
            { key: 'velocity_max', label: 'Velocity Max', type: 'number', default: 9999, tooltip: 'Maximum velocity threshold' },
            { key: 'velocity_count', label: 'Velocity Count', type: 'number', default: 10, tooltip: 'Number of frames to average for velocity calculation' },
            { key: 'directions', label: 'Directions', type: 'string_list', default: [], tooltip: 'Expected directions, e.g. N, NE, E, SE, S, SW, W, NW' },
            { key: 'direction_count', label: 'Direction Count', type: 'number', default: 10, tooltip: 'Number of frames to average for direction calculation' },
            { key: 'count_min', label: 'Count Min', type: 'number', default: 0, tooltip: 'Minimum object count threshold' },
            { key: 'count_max', label: 'Count Max', type: 'number', default: 1, tooltip: 'Maximum object count before triggering too many alert' },
            { key: 'time_min', label: 'Time Min', type: 'number', default: 0, tooltip: 'Minimum time (seconds) an object must be present' },
            { key: 'time_max', label: 'Time Max', type: 'number', default: 0, tooltip: 'Maximum time (seconds) before triggering congestion alert' },
            { key: 'time_duration', label: 'Time Duration', type: 'number', default: 0, tooltip: 'Duration window (seconds) for time-based triggers' }
        ]
    }
];
